
public class problem2 {

	/**
	 * Problem 2
	 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	 * By starting with 1 and 2, the first 10 terms will be
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
	 * find the sum of the even-valued terms.
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		long n = 4000000,sum = 0;
		long[] fib = new long[(int) n];
		
		fib[0] = 0;
		fib[1] = 1;
		
		for(int i =2;i<n;i++){
			fib[i] = fib[i-1] + fib[i-2];
			if(fib[i] %2 == 0){
				sum += fib[i];
				if(sum > 4000000){
					break;
				}
				
			}
		}
		
		System.out.print(sum);
	}

}
